In [1]:
print("hello")

hello


Import Library : Numpy


In [4]:
import numpy as np
#check version
print(np.__version__)

2.5.2


# DataType of numpy

ndarray

In [2]:
import numpy as np

#1-dimensional array , as a vector
a1 = np.array([1, 2, 3])
a1.shape , a1.dtype , a1.ndim, type(a1)

((3,), dtype('int64'), 1, numpy.ndarray)

In [4]:
# 2- dimensional array , as a matrix
a2 = np.array([
    [1,2,3],
    [4,5,6]
])
a2.shape , a2.dtype , a2.ndim , type(a2)

((2, 3), dtype('int64'), 2, numpy.ndarray)

In [ ]:

a3 = np.array([
    [
        [1,2,3],
        [4,5,6],
        [7,8,9],
        
    ] 
    
])
a3.shape , a3.dtype , a3.ndim , type(a3)

((1, 2, 3), dtype('int64'), 3, numpy.ndarray)

# Anatomy of array 

Array : A list of number can be multiple dimension
Scalar : a single number 
Vector : a list of number with 1 dimenstion (1-d array)
Matrix : a list  of multiple dimension (n-d array)

# Attribute of an array

.shape : the exact size along each dimension (Rows, Column)
.ndim : the total number of dimensions
.dtype : the type of data stored inside 
.size : the total count of all elements inside

# Creation of an array

In [3]:
import numpy as np

simple_array = np.array([1, 2, 3])
simple_array

array([1, 2, 3])

In [4]:
simple_array.dtype

dtype('int64')

In [5]:
ones = np.ones([3,2])
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [6]:
ones.astype(int)

array([[1, 1],
       [1, 1],
       [1, 1]])

In [7]:
zeros = np.zeros([5,3])
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [8]:
zeros.astype(int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

# Create a ranage within a range value  

In [14]:
range_array = np.arange(0,10)
range_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
#random array
random_array = np.random.randint(5 , size=(5,3))
random_array

array([0, 4, 4, 1, 4], dtype=int32)

# Arethmatics operator :

In [30]:
a2

NameError: name 'a2' is not defined