In [1]:
print("hello")

hello


Import Library : Numpy


In [4]:
import numpy as np
#check version
print(np.__version__)

2.5.2


# DataType of numpy

ndarray

In [32]:
import numpy as np

#1-dimensional array , as a vector
a1 = np.array([1, 2, 3])
a1.shape , a1.dtype , a1.ndim, type(a1)
a1

array([1, 2, 3])

In [34]:
# 2- dimensional array , as a matrix
a2 = np.array([
    [1,2,3],
    [4,5,6]
])
a2.shape , a2.dtype , a2.ndim , type(a2)
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:

a3 = np.array([
    [
        [1,2,3],
        [4,5,6],
        [7,8,9],
        
    ] 
    
])
a3.shape , a3.dtype , a3.ndim , type(a3)
a3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

# Anatomy of array 

Array : A list of number can be multiple dimension
Scalar : a single number 
Vector : a list of number with 1 dimenstion (1-d array)
Matrix : a list  of multiple dimension (n-d array)

# Attribute of an array

.shape : the exact size along each dimension (Rows, Column)
.ndim : the total number of dimensions
.dtype : the type of data stored inside 
.size : the total count of all elements inside

# Creation of an array

In [3]:
import numpy as np

simple_array = np.array([1, 2, 3])
simple_array

array([1, 2, 3])

In [4]:
simple_array.dtype

dtype('int64')

In [5]:
ones = np.ones([3,2])
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [6]:
ones.astype(int)

array([[1, 1],
       [1, 1],
       [1, 1]])

In [7]:
zeros = np.zeros([5,3])
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [8]:
zeros.astype(int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

# Create a ranage within a range value  

In [7]:
import numpy as np

range_array = np.arange(0, 10)
range_array

array([0, 2, 4, 6, 8])

In [27]:
#random array
random_array = np.random.randint(5 , size=(5,3))
random_array

array([0, 4, 4, 1, 4], dtype=int32)

# Arethmatics operator :

In [33]:
a1

array([1, 2, 3])

In [36]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [37]:
#add
a1 + ones

array([2., 3., 4.])

In [38]:
#subtract
a1 - ones

array([0., 1., 2.])

In [39]:
#divide
a1 / ones

array([1., 2., 3.])

In [40]:
#multiply
a1 * a2

array([[ 1,  4,  9],
       [ 4, 10, 18]])

In [22]:
#sum
np.sum(a1)

np.int64(6)

In [42]:
#exponential 
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [43]:
#logarithm 
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

In [44]:
#dot product _ np.dot()
a = np.array([1, 2 , 3])
b = np.array([4, 5 , 6])

np.dot(a,b)

np.int64(32)

In [45]:
#mean
np.mean(a1)

np.float64(2.0)

In [46]:
#standard deviation
np.std( a1)

np.float64(0.816496580927726)

In [47]:
#variance
np.var(a)

np.float64(0.6666666666666666)

# Indexing 

In [9]:
a4 = np.random.randint(10 , size = (2 , 2 , 5 , 4))
a4

array([[[[8, 0, 1, 7],
         [8, 2, 4, 6],
         [3, 6, 9, 4],
         [1, 8, 6, 7],
         [6, 1, 2, 6]],

        [[5, 0, 1, 1],
         [9, 6, 5, 3],
         [3, 5, 0, 0],
         [6, 7, 1, 5],
         [6, 8, 7, 4]]],


       [[[6, 9, 1, 9],
         [2, 0, 6, 5],
         [3, 5, 7, 9],
         [2, 7, 5, 7],
         [2, 0, 5, 5]],

        [[0, 3, 5, 9],
         [3, 2, 7, 7],
         [9, 2, 4, 2],
         [9, 4, 4, 4],
         [3, 2, 1, 3]]]], dtype=int32)

In [13]:
a4[0]

array([[[8, 0, 1, 7],
        [8, 2, 4, 6],
        [3, 6, 9, 4],
        [1, 8, 6, 7],
        [6, 1, 2, 6]],

       [[5, 0, 1, 1],
        [9, 6, 5, 3],
        [3, 5, 0, 0],
        [6, 7, 1, 5],
        [6, 8, 7, 4]]], dtype=int32)

In [21]:
a1 = np.array([1, 2, 3])
a1[2]

np.int64(3)

# Reshaping and Transpose

In [23]:
#Reshaping
a1

array([1, 2, 3])

In [26]:
a1.reshape(1,3,1)

array([[[1],
        [2],
        [3]]])

In [29]:
#Transpose
a4.T

NameError: name 'a2' is not defined